### ISSUE TITLE
images des logos n'apparaissent pas sur Firefox pour l'inscription

### ISSUE THREAD

**Issue by lydies** [alberto56/minisite-sommet-tdj#7]
sur les pages de l'inscription comme celle-ci : http://sommet.terredesjeunes.org/inscription/sud-statut.html

**Comment by alberto56** [comment]
Voir http://stackoverflow.com/questions/12941953/image-in-content-field-from-selector-before-not-working-in-firefox
L'utilisation précédente n'est pas valide: J'ai enlevé les propriétés no-repeat etc. et maintenant ça marche.
